### ISSUE TITLE
php "Still waiting for db to be ready"

### ISSUE THREAD

**Issue by BurningDog** [dunglas/symfony-docker#94]
I'm running Ubuntu 20. I added a mysql container to `docker-compose.yml`:

```yaml
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306"
    networks:
        - mysql
```

...but when running `docker-compose up` I got plenty of these errors from the php container, even though the mysql container was ready:

`Still waiting for db to be ready.`

The (bizarre) fix is to do `chmod +x bin/console` - see https://github.com/api-platform/api-platform/issues/1656 (and yes, I have API Platform in my Symfony installation).

**Comment by BurningDog** [comment]
The executable is required because https://github.com/dunglas/symfony-docker/blob/master/docker/php/docker-entrypoint.sh#L35 does `bin/console doctrine:query:sql "SELECT 1"` instead of `php bin/console doctrine:query:sql "SELECT 1"`

**Comment by henryosim** [comment]
having same issue on macOS. cloned repo added symfony/orm-pack and ran `docker-compose up`, i get this messages

`php_1       | Still waiting for db to be ready... Or maybe the db is not reachable. 57 attempts left
database_1  | 2020-12-20 07:26:01.808 UTC [94] FATAL:  password authentication failed for user "symfony"
database_1  | 2020-12-20 07:26:01.808 UTC [94] DETAIL:  Role "symfony" does not exist.
database_1  |   Connection matched pg_hba.conf line 99: "host all all all md5"
php_1       | Still waiting for db to be ready... Or maybe the db is not reachable. 56 attempts left
database_1  | 2020-12-20 07:26:03.385 UTC [95] FATAL:  password authentication failed for user "symfony"
database_1  | 2020-12-20 07:26:03.385 UTC [95] DETAIL:  Role "symfony" does not exist.
database_1  |   Connection matched pg_hba.conf line 99: "host all all all md5"
`

**Comment by BurningDog** [comment]
@henryosim I know the docs in this repo say that if you add `symfony/orm-pack` then `symfony-docker` will add a database docker image (I think postgres), but I rather added a docker `mysql` image manually to my `docker-compose.yml` (see the issue description in this thread). If you do a `docker ps` do you see a mysql/postgres image? If not, then add it and run `docker-compose up` again.

If you do have a container, rather than putting `chmod +x bin/console` in your entrypoint file, run it on your Symfony codebase (or change line 35 of `entrypoint.sh` to

`until [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ] || php bin/console doctrine:query:sql "SELECT 1" > /dev/null 2>&1; do`

**Comment by henryosim** [comment]
@BurningDog `symfony/orm-pack ` added a postgres image and i can see the postgres container when i run `docker-compose ps`. 

Did you mean i should run `chmod +x bin/console` on the container like this `docker-compose exec php chmod +x bin/console`?  i have tried that and i am getting same issue.

i have also updated line 35 of entrypoint to `until [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ] || php bin/console doctrine:query:sql "SELECT 1" > /dev/null 2>&1; do`. I am still getting 
`php_1       | Still waiting for db to be ready... Or maybe the db is not reachable. 52 attempts left
database_1  | 2020-12-21 07:06:00.289 UTC [226] FATAL:  password authentication failed for user "symfony"
database_1  | 2020-12-21 07:06:00.289 UTC [226] DETAIL:  Role "symfony" does not exist.
database_1  |   Connection matched pg_hba.conf line 99: "host all all all md5"
php_1       | Still waiting for db to be ready... Or maybe the db is not reachable. 51 attempts left
database_1  | 2020-12-21 07:06:01.965 UTC [227] FATAL:  password authentication failed for user "symfony"
database_1  | 2020-12-21 07:06:01.965 UTC [227] DETAIL:  Role "symfony" does not exist.
database_1  |   Connection matched pg_hba.conf line 99: "host all all all md5"`

in your docker-compose.yml i noticed you added a network option, is that needed for the database to work? i believe docker uses a default network when none is specified ?

**Comment by BurningDog** [comment]
I added a network option, yes - both to my mysql container and to the php container in order for it to be able to access mysql. Here's my full `docker-compose.yml`:

```
version: "3.4"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - mysql

  redis:
    image: "redis:alpine"
    build:
      context: .
      target: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - redis

  php:
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - public:/srv/app/public
    networks:
      - mysql
      - php
      - redis
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: ${DATABASE_URL}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_PUBLISH_URL: ${MERCURE_URL:-http://caddy/.well-known/mercure}
      SYMFONY_VERSION:
      GIT_SHA: ${GIT_SHA}

  caddy:
    build:
      context: .
      target: symfony_caddy
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT: ${MERCURE_PUBLISHER_JWT:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT: ${MERCURE_SUBSCRIBER_JWT:-!ChangeMe!}
      PHP_CONTAINER: ${PHP_CONTAINER}
    restart: unless-stopped
    networks:
      - mysql
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - public:/srv/app/public

volumes:
  caddy_data:
  caddy_config:
  my-db:
  public:
  redis:

networks:
  mysql:
  php:
  redis:
```

I added redis because I want to do session management inside redis, so feel free to ignore that bit.

If you shell into your `php` container you should be able to `ping mysql` and get a response (`mysql` being the network name - in your case it will be the name of the network you add to the postgres container e.g. `postgres`). Once that works, do a command line login to postgres within your `php` container (you may need to temporarily install the postgres command line tools within the container). If that works, then manually run the command inside the `php` container: `php bin/console doctrine:query:sql "SELECT 1"`

Only once all of those are working, do the `docker-compose up` again.

**Comment by BurningDog** [comment]
And I should mention that I didn't just run `docker-compose up`, I run:

```
SYMFONY_VERSION=4.4.* PHP_VERSION=7.4 SERVER_NAME="example.com" docker-compose --env-file=.env.local -f docker-compose.yml -f docker-compose.prod.yml up -d
```

That sets up all of the things I need for full production use, although since you're running locally you don't need the `-f docker-compose.prod.yml`.

**Comment by henryosim** [comment]
noted, thanks

**Comment by maxhelias** [comment]
@BurningDog see #100 that should fix the problem.

FYI, You can disable adding docker images in composer.json file with `extra.symfony.docker`

**Comment by thePanz** [comment]
@maxhelias Looks like the fix in #100 does not take into consideration if the environment is commented out :see_no_evil: :smile:

**Comment by maxhelias** [comment]
Great ! Thanks @thePanz 🎉 

I think now we can close the issue. Don't hesitate to re-open it if there are still things missing.

**Comment by Vandersteen** [comment]
This issue is still happening for me on windows.

* Fresh Docker desktop install
* Clone from repo (using github desktop)
* docker compose up

-> All commands like:

```
docker compose exec php bin/console
```

Fail with error

> docker compose exec php bin/console
> ': No such file or directory

 Any command i want to run i need to add `php` in front.
 
 I also had to change the entrypoint.sh L45 and L66 to use `php <rest of command>` for the containers to start
 
 I tried `chmod +x bin/console` in wsl, git bash + in container -> no changes

**Comment by Vandersteen** [comment]
I found another way to solve it:

running

```
#This one was missing
dos2unix.exe bin/console

#also
dos2unix.exe Dockerfile
dos2unix.exe docker/php/*.sh
```

Then it works with the default settings

**Comment by Sercurio** [comment]
Same error here.
I'm on MacOS and I can launch `php bin/console doctrine:query:sql "SELECT 1"`from the php container with a correct response, but the php container log hold on still wiating for db to be ready

**Comment by maxhelias** [comment]
@Sercurio Your `bin/console` file probably doesn't have execution rights for some reason.
